# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='机构名')),
                ('address', models.CharField(max_length=50, verbose_name='机构地址')),
                ('tel', models.CharField(max_length=11, verbose_name='电话号码')),
                ('opentime', models.CharField(max_length=30, verbose_name='开课时间')),
                ('desc', models.TextField(verbose_name='机构介绍')),
                ('click_nums', models.IntegerField(verbose_name='机构点击量')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='category/%Y/%m', verbose_name='校区展示')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机构图片',
                'verbose_name_plural': '机构图片',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='教师名')),
                ('teach_time', models.IntegerField(max_length=10, verbose_name='教学时间')),
                ('teach_grade', models.CharField(max_length=10, verbose_name='擅长科目')),
                ('glory', models.CharField(max_length=200, verbose_name='教师荣誉')),
                ('desc', models.CharField(max_length=200, verbose_name='教师介绍')),
                ('education', models.CharField(max_length=200, verbose_name='教师背景')),
                ('motto', models.CharField(max_length=200, verbose_name='教师格言')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='TeacherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='category/%Y/%m', verbose_name='校区展示')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '教师风采',
                'verbose_name_plural': '教师风采',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.TeacherImage', verbose_name='名师风采'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.CategoryImage', verbose_name='校园展示'),
        ),
    ]
