# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='teacherimage',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Teacher', verbose_name='教师'),
        ),
    ]
