# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('shop_price', models.IntegerField(verbose_name='市场价格')),
                ('py_price', models.IntegerField(verbose_name='便宜价格')),
                ('lessons', models.IntegerField(verbose_name='课次')),
                ('people', models.IntegerField(verbose_name='开课人数')),
                ('open_time', models.CharField(max_length=20, verbose_name='开课时间')),
                ('desc', models.TextField(verbose_name='课程介绍')),
                ('teach_desc', models.TextField(verbose_name='教学内容')),
                ('teach_feature', models.TextField(verbose_name='教学特定')),
                ('teach_target', models.TextField(verbose_name='教育目标')),
                ('image', models.ImageField(max_length=200, upload_to='courses/%Y/%m')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('std_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('is_fun', models.BooleanField(default=False, verbose_name='是否周末')),
                ('teach_way', models.CharField(choices=[('one to one', '一对一'), ('one to two', '一对二'), ('one to three', '一对三'), ('small people', '小班')], max_length=15, verbose_name='授课方式')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('xx', '小学'), ('cz', '初中'), ('gz', '高中'), ('dx', '大学')], max_length=3)),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学历',
                'verbose_name_plural': '学历',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='年级')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Education', verbose_name='学历')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='科目名')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='lesson_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='科目'),
        ),
    ]
